version: 2

updates:
- package-ecosystem: npm
  directory: "/backend"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
